/****************************************************************************
 *
 *
 *  Project: GNU MP (GMP) 6.3.0
 *  Source files:
 *    gmp-impl.h
 *    gmp-h.in
 *    sieve_table.h
 *
 *
 *  The original file copyright and license notices follow.
 *
 *
 * gmp-impl.h
 *
 * Include file for internal GNU MP types and definitions.
 *
 *    THE CONTENTS OF THIS FILE ARE FOR INTERNAL USE AND ARE ALMOST CERTAIN TO
 *    BE SUBJECT TO INCOMPATIBLE CHANGES IN FUTURE GNU MP RELEASES.
 *
 * Copyright 1991-2018, 2021, 2022 Free Software Foundation, Inc.
 *
 * This file is part of the GNU MP Library.
 *
 * The GNU MP Library is free software; you can redistribute it and/or modify
 * it under the terms of either:
 *
 *   * the GNU Lesser General Public License as published by the Free
 *     Software Foundation; either version 3 of the License, or (at your
 *     option) any later version.
 *
 * or
 *
 *   * the GNU General Public License as published by the Free Software
 *     Foundation; either version 2 of the License, or (at your option) any
 *     later version.
 *
 * or both in parallel, as here.
 *
 * The GNU MP Library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * for more details.
 *
 * You should have received copies of the GNU General Public License and the
 * GNU Lesser General Public License along with the GNU MP Library.  If not,
 * see https://www.gnu.org/licenses/.
 *
 *
 * gmp-h.in
 *
 * Definitions for GNU multiple precision functions.   -*- mode: c -*-
 *
 * Copyright 1991, 1993-1997, 1999-2016, 2020, 2021 Free Software
 * Foundation, Inc.
 *
 * This file is part of the GNU MP Library.
 *
 * The GNU MP Library is free software; you can redistribute it and/or modify
 * it under the terms of either:
 *
 *   * the GNU Lesser General Public License as published by the Free
 *     Software Foundation; either version 3 of the License, or (at your
 *     option) any later version.
 *
 * or
 *
 *   * the GNU General Public License as published by the Free Software
 *     Foundation; either version 2 of the License, or (at your option) any
 *     later version.
 *
 * or both in parallel, as here.
 *
 * The GNU MP Library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * for more details.
 *
 * You should have received copies of the GNU General Public License and the
 * GNU Lesser General Public License along with the GNU MP Library.  If not,
 * see https://www.gnu.org/licenses/.
 *
 *
 * sieve_table.h
 *
 * This file generated by gen-sieve.c - DO NOT EDIT.
 *
 */

#ifndef KERNELS_44_GMP_PRIMESIEVE_INCLUDE_KERNEL_H_
#define KERNELS_44_GMP_PRIMESIEVE_INCLUDE_KERNEL_H_

/*
 * gmp-h.in:41-50
 */
#if !defined(__GMP_WITHIN_CONFIGURE)
#define __GMP_HAVE_HOST_CPU_FAMILY_power 0
#define __GMP_HAVE_HOST_CPU_FAMILY_powerpc 0
#define GMP_LIMB_BITS 64
#define GMP_NAIL_BITS 0
#endif
#define GMP_NUMB_BITS (GMP_LIMB_BITS - GMP_NAIL_BITS)
#define GMP_NUMB_MASK ((~__GMP_CAST(mp_limb_t, 0)) >> GMP_NAIL_BITS)
#define GMP_NUMB_MAX GMP_NUMB_MASK
#define GMP_NAIL_MASK (~GMP_NUMB_MASK)

/*
 * gmp-h.in:134-146
 */
#ifdef __GMP_SHORT_LIMB
typedef unsigned int mp_limb_t;
typedef int mp_limb_signed_t;
#else
#ifdef _LONG_LONG_LIMB
typedef unsigned long long int mp_limb_t;
typedef long long int mp_limb_signed_t;
#else
typedef unsigned long int mp_limb_t;
typedef long int mp_limb_signed_t;
#endif
#endif
typedef unsigned long int mp_bitcnt_t;

/*
 * gmp-h.in:167-178
 */
typedef mp_limb_t *mp_ptr;
typedef const mp_limb_t *mp_srcptr;
#if defined(_CRAY) && !defined(_CRAYMPP)
#define __GMP_MP_SIZE_T_INT 1
typedef int mp_size_t;
typedef int mp_exp_t;
#else
#define __GMP_MP_SIZE_T_INT 0
typedef long int mp_size_t;
typedef long int mp_exp_t;
#endif

/*
 * gmp-h.in:249-251
 */
#ifndef __MPN
#define __MPN(x) __gmpn_##x
#endif

/*
 * gmp-h.in:297-302
 */
#if defined(__GNUC__) && defined(__GNUC_MINOR__)
#define __GMP_GNUC_PREREQ(maj, min)                                            \
    ((__GNUC__ << 16) + __GNUC_MINOR__ >= ((maj) << 16) + (min))
#else
#define __GMP_GNUC_PREREQ(maj, min) 0
#endif

/*
 * gmp-h.in:309-313
 */
#if __GMP_GNUC_PREREQ(2, 96) && !defined(__GMP_NO_ATTRIBUTE_CONST_PURE)
#define __GMP_ATTRIBUTE_PURE __attribute__((__pure__))
#else
#define __GMP_ATTRIBUTE_PURE
#endif

/*
 * gmp-h.in:323-327
 */
#ifdef __cplusplus
#define __GMP_CAST(type, expr) (static_cast<type>(expr))
#else
#define __GMP_CAST(type, expr) ((type)(expr))
#endif

/*
 * gmp-h.in:347-355
 */
#if defined(__cplusplus)
#if __cplusplus >= 201103L
#define __GMP_NOTHROW noexcept
#else
#define __GMP_NOTHROW throw()
#endif
#else
#define __GMP_NOTHROW
#endif

/*
 * gmp-h.in:120-131
 */
#if __GMP_LIBGMP_DLL
#ifdef __GMP_WITHIN_GMP
#define __GMP_DECLSPEC __GMP_DECLSPEC_EXPORT
#else
#define __GMP_DECLSPEC __GMP_DECLSPEC_IMPORT
#endif
#else
#define __GMP_DECLSPEC
#endif

/*
 * gmp-impl.h:539-540
 */
#undef MIN
#define MIN(l, o) ((l) < (o) ? (l) : (o))

/*
 * gmp-impl.h:568
 */
#define MP_LIMB_T_MAX (~(mp_limb_t)0)

/*
 * gmp-impl.h:2507-2511
 */
#if WANT_ASSERT
#define ASSERT(expr) ASSERT_ALWAYS(expr)
#else
#define ASSERT(expr)                                                           \
    do {                                                                       \
    } while (0)
#endif

/*
 * gmp-impl.h:4002-4006
 */
#if defined _LONG_LONG_LIMB
#define CNST_LIMB(C) ((mp_limb_t)C##LL)
#else
#define CNST_LIMB(C) ((mp_limb_t)C##L)
#endif

/*
 * gmp-impl.h:2143-2144
 */
#define gmp_primesieve __gmp_primesieve
__GMP_DECLSPEC mp_limb_t gmp_primesieve(mp_ptr, mp_limb_t);

/*
 * gmp-h.in:1576-1577
 */
#define mpn_popcount __MPN(popcount)
__GMP_DECLSPEC mp_bitcnt_t mpn_popcount(mp_srcptr, mp_size_t)
__GMP_NOTHROW __GMP_ATTRIBUTE_PURE;

/*
 * sieve_table.h:7-36
 * Generated in the GMP project root by gen-sieve.c with limb_bits=64;
 * compare against the in-tree-build artifact, not the 32-bit output.
 */
#define PRIMESIEVE_INIT_TABLE                                                  \
    CNST_LIMB(0x3294C9E069128480), CNST_LIMB(0x95A35E1EC4AB21DC),              \
        CNST_LIMB(0x4AD7CE99B8693366), CNST_LIMB(0x6595B6DA728DC52B),          \
        CNST_LIMB(0xEA6D9F8787B0CEDE), CNST_LIMB(0x3F56A1F4CD3275A9),          \
        CNST_LIMB(0xFD3848FB74A76ADB), CNST_LIMB(0xDBBA0DD1A1EDF6AF),          \
        CNST_LIMB(0xCEC7F17ED22799A5), CNST_LIMB(0xEAEC17BDBB717D56),          \
        CNST_LIMB(0x3B0EB7B3585AFCF3), CNST_LIMB(0xE563D8F69FDF6C4F),          \
        CNST_LIMB(0xFE5BA7ABA45E92FC), CNST_LIMB(0x158DEE6F3BF49B7D),          \
        CNST_LIMB(0xBE5A7BC4EDE6CD1A), CNST_LIMB(0xD7679B3FCA7BB6AD),          \
        CNST_LIMB(0xC3F66B971FEF37E9), CNST_LIMB(0x6F7EBCF339C953FD),          \
        CNST_LIMB(0xD5A5ECDCD235DBF0), CNST_LIMB(0xECFA7B2FD5B65E3B),          \
        CNST_LIMB(0xD28EFDF9C89F67B1), CNST_LIMB(0xCB7F7C7A3DD3AF4F),          \
        CNST_LIMB(0xEEBED6CDFF6B32CC), CNST_LIMB(0xD5BD73F85ECFA97C),          \
        CNST_LIMB(0x21FDBE4FBBAD48F7), CNST_LIMB(0x5E35A3B5EEB7FDE7),          \
        CNST_LIMB(0xD9EBFD53A7DBBCC9), CNST_LIMB(0xFF9EDEAF2EFE1F76),
#define PRIMESIEVE_NUMBEROF_TABLE 28

/* sieve_table.h:41-45 */
#define SIEVE_MASK1 CNST_LIMB(0x3204C1A049120485)
#define SIEVE_MASKT CNST_LIMB(0xA1204892058)
#define SIEVE_2MSK1 CNST_LIMB(0x29048402110840A)
#define SIEVE_2MSK2 CNST_LIMB(0x9402180C40230184)
#define SIEVE_2MSKT CNST_LIMB(0x5021088402120)

#endif // KERNELS_44_GMP_PRIMESIEVE_INCLUDE_KERNEL_H_
