#include "../include/kernel.h"
#include <cstdio>
#include <cstring>

int ossl_sm4_set_key_rvv(const uint8_t *, SM4_KEY *);
void ossl_sm4_encrypt_rvv(const uint8_t *, uint8_t *, const SM4_KEY *);
void ossl_sm4_decrypt_rvv(const uint8_t *, uint8_t *, const SM4_KEY *);

static uint32_t state = 0x67a4f012U;
static uint32_t next() {
    state ^= state << 13;
    state ^= state >> 17;
    state ^= state << 5;
    return state;
}

static bool known_vectors() {
    // OpenSSL 4.0.2 test/sm4_internal_test.c: GB/T 32907-2016 Example 1.
    const uint8_t plain[16] = {0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef,
                               0xfe, 0xdc, 0xba, 0x98, 0x76, 0x54, 0x32, 0x10};
    const uint8_t expected[16] = {0x68, 0x1e, 0xdf, 0x34, 0xd2, 0x06, 0x96, 0x5e,
                                  0x86, 0xb3, 0xe9, 0x4f, 0x53, 0x6e, 0x42, 0x46};
    // OpenSSL test/recipes/30-test_evp_data/evpciph_sm4.txt: first CBC block
    // with IV = plain, so the raw block cipher encrypts 16 zero bytes.
    const uint8_t cbc_first[16] = {0x26, 0x77, 0xf4, 0x6b, 0x09, 0xc1, 0x22, 0xcc,
                                   0x97, 0x55, 0x33, 0x10, 0x5b, 0xd4, 0xa2, 0x2a};
    const uint8_t zero[16] = {};
    SM4_KEY scalar{}, rvv{};
    uint8_t a[16], b[16];
    if (ossl_sm4_set_key(plain, &scalar) != 1 ||
        ossl_sm4_set_key_rvv(plain, &rvv) != 1 ||
        std::memcmp(&scalar, &rvv, sizeof scalar)) return false;
    for (int i = 0; i < 2; ++i) {
        const uint8_t *input = i ? zero : plain;
        const uint8_t *ciphertext = i ? cbc_first : expected;
        ossl_sm4_encrypt(input, a, &scalar);
        ossl_sm4_encrypt_rvv(input, b, &rvv);
        if (std::memcmp(a, ciphertext, 16) || std::memcmp(b, ciphertext, 16))
            return false;
        ossl_sm4_decrypt(ciphertext, a, &scalar);
        ossl_sm4_decrypt_rvv(ciphertext, b, &rvv);
        if (std::memcmp(a, input, 16) || std::memcmp(b, input, 16))
            return false;
    }
    return true;
}

static bool trial(int n, int mode) {
    struct Data {
        uint8_t key[16];
        uint8_t input[48];
        uint8_t output[48];
        SM4_KEY schedule;
        uint8_t guard[16];
    } a{}, b{};
    for (uint8_t &v : a.key) v = uint8_t(next());
    for (uint8_t &v : a.input) v = uint8_t(next());
    for (uint8_t &v : a.output) v = uint8_t(next());
    for (uint32_t &v : a.schedule.rk) v = next();
    for (uint8_t &v : a.guard) v = uint8_t(next());
    if (n == 0) std::memset(&a, 0, sizeof a);
    if (n == 1) std::memset(&a, 0xff, sizeof a);
    b = a;

    // The source reads the complete key before storing any round keys.
    const uint8_t *ka = mode == 4 ? reinterpret_cast<uint8_t *>(&a.schedule) : a.key;
    const uint8_t *kb = mode == 4 ? reinterpret_cast<uint8_t *>(&b.schedule) : b.key;
    if (ossl_sm4_set_key(ka, &a.schedule) != 1 ||
        ossl_sm4_set_key_rvv(kb, &b.schedule) != 1 ||
        std::memcmp(&a, &b, sizeof a)) {
        std::fprintf(stderr, "SM4 key mismatch trial=%d mode=%d\n", n, mode);
        return false;
    }
    // Also exercise arbitrary user-provided schedules, rather than only those
    // generated by set_key; either direction accepts all 32 raw round words.
    if (n & 1) {
        for (uint32_t &v : a.schedule.rk) v = next();
        b.schedule = a.schedule;
    }

    const uint8_t *in_a = a.input + 8, *in_b = b.input + 8;
    uint8_t *out_a = a.output + 8, *out_b = b.output + 8;
    if (mode == 1) { out_a = a.input + 8; out_b = b.input + 8; }
    if (mode == 2) { out_a = a.input + 11; out_b = b.input + 11; }
    if (mode == 3) {
        out_a = reinterpret_cast<uint8_t *>(&a.schedule) + 4;
        out_b = reinterpret_cast<uint8_t *>(&b.schedule) + 4;
    }
    if (n & 2) {
        ossl_sm4_decrypt(in_a, out_a, &a.schedule);
        ossl_sm4_decrypt_rvv(in_b, out_b, &b.schedule);
    } else {
        ossl_sm4_encrypt(in_a, out_a, &a.schedule);
        ossl_sm4_encrypt_rvv(in_b, out_b, &b.schedule);
    }
    if (std::memcmp(&a, &b, sizeof a)) {
        std::fprintf(stderr, "SM4 block mismatch trial=%d mode=%d seed=0x67a4f012\n",
                     n, mode);
        return false;
    }
    return true;
}

int main() {
    if (!known_vectors()) {
        std::fputs("SM4 OpenSSL known vectors failed\n", stderr);
        return 1;
    }
    for (int n = 0; n < 300; ++n)
        for (int mode = 0; mode < 5; ++mode)
            if (!trial(n, mode)) return 1;
    std::puts("SM4: known ECB/CBC vectors and 1500 differential cases passed");
}
